### ISSUE TITLE
"NO_RESERVATION" error due to short reservationTtl in relay configuration

### ISSUE THREAD

**Issue by PradaJoaquin** [haydenyoung/orbitdb-browser-example#1]
Hi,

I encountered the NO_RESERVATION error while trying to fetch a database from Browser B in the final step of the example.

After investigating, I noticed that Node A's reservation was being dropped by the relay, likely because of the short reservationTtl value in the relay configuration. By default, the reservationTtl is set to 1000ms (1 second).

Here is the original configuration in the [relay.js](https://github.com/orbitdb/orbitdb/blob/main/test/utils/relay.js) file from @orbitdb/core package:

```js
relay: circuitRelayServer({
      reservations: {
        maxReservations: 5000,
        reservationTtl: 1000,
        defaultDataLimit: BigInt(1024 * 1024 * 1024)
      }
    })
```
I updated the reservationTtl value to 3600000ms (1 hour), big value for testing purposes, as shown below:

```js
relay: circuitRelayServer({
      reservations: {
        maxReservations: 5000,
        reservationTtl: 3600000,
        defaultDataLimit: BigInt(1024 * 1024 * 1024)
      }
    })
```
With this change, the NO_RESERVATION error was resolved, and Browser B successfully fetched the database.

Would increasing the reservationTtl in this way be the correct approach to solve this issue? Or is there a recommended alternative?

**Comment by haydenyoung** [comment]
I believe in the latest versions of CircuitRelayServer they have bumped up the default values to be more generous. In particular I think the default ttl is something like 2 hours. Therefore, I would suggest trying relay with nothing set, i.e.

`relay: circuitRelayServer()`

and see how that goes.

**Comment by PradaJoaquin** [comment]
Yes, it works perfectly with the default settings.

I'd be happy to create a PR in the OrbitDB repository to update the relay example to use the default configuration. Would you be okay with that?

**Comment by haydenyoung** [comment]
Yes, please feel free to provide any PRs.
